CREATE TABLE "flyway_test_table" (
	ID NUMBER PRIMARY KEY,
	FIRSTNAME varchar(255) default NULL,
	LASTNAME varchar(255) default NULL,
	MAIL varchar(255) default NULL
);

CREATE SEQUENCE "KEY_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

